name: "Setup"
description: "Setup node"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: "npm"
        cache-dependency-path: package-lock.json
